In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
sns.set_style('darkgrid')
mpl.rcParams['figure.figsize'] = [18,10]

### Performing element-wise multiplication
Element-wise multiplication in TensorFlow is performed using two tensors with identical shapes. This is because the operation multiplies elements in corresponding positions in the two tensors. An example of an element-wise multiplication, denoted by the ⊙ symbol, is shown below:

$$\begin{bmatrix}
    1 & 2 \\
    2 & 1 
    \end{bmatrix}     \odot  \begin{bmatrix} 3 & 2 \\1 & 5\end{bmatrix}  = \begin{bmatrix}3 & 4 \\2 & 5 \end{bmatrix} $$    


In [3]:
from tensorflow import constant, multiply, ones_like, ones

# Define tensors A1 and A23 as constants
A1 = constant([1, 2, 3, 4])
A23 = constant([[1, 2, 3], [1, 6, 4]])
A23.shape

# Define B1 and B23 to have the correct shape
B1 = ones_like(A1)
B23 = ones_like(A23)

# Perform element-wise multiplication
C1 = multiply(A1, B1)
C23 = multiply(A23, B23)

# Print the tensors C1 and C23
print('C1: {}'.format(C1.numpy()))
print('C23: {}'.format(C23.numpy()))

C1: [1 2 3 4]
C23: [[1 2 3]
 [1 6 4]]


In [5]:
from tensorflow import matmul
# Define features, params, and bill as constants
features = constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = constant([[1000], [150]])
bill = constant([[3913], [2682], [8617], [64400]])

# Compute billpred using features and params
billpred = matmul(features, params)

# Compute and print the error
error = bill - billpred
print(error.numpy())

[[-1687]
 [-3218]
 [-1933]
 [57850]]


In [9]:
wealth = constant([[11, 50],
       [ 7,  2],
       [ 4, 60],
       [ 3,  0],
       [25, 10]])
wealth

<tf.Tensor: id=20, shape=(5, 2), dtype=int32, numpy=
array([[11, 50],
       [ 7,  2],
       [ 4, 60],
       [ 3,  0],
       [25, 10]], dtype=int32)>

In [13]:
from tensorflow import reduce_sum

w_all = reduce_sum(wealth)
w_all.numpy()

172

In [15]:
w_1 = reduce_sum(wealth, 0)
w_1.numpy()

array([ 50, 122], dtype=int32)

In [17]:
w_2 = reduce_sum(wealth, 1)
w_2.numpy()

array([61,  9, 64,  3, 35], dtype=int32)

### Overview of advanced operations

|Operation|Use|
|---|---|
|`gradient()`| Computes the slope of a function at a point|
|`reshape()`| Reshapes a tensor (eg 10x10 to 100x1) |
|`random()`| Populates tensor with entries drawn from a probabilty distribution | 


- In many problems, we will want to find the optimum of a function
    - **Minimum:** Lowest value of a loss function 
    - **Maximum:** Highest value of objective function 
- We can do this using the `gradient()` operation
    - 

