In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
sns.set_style('darkgrid')
mpl.rcParams['figure.figsize'] = [18,10]

### The linear regression model 

- How do we get from a linear regression model to a neural network?
    - By adding a hidden layer
    - A Dense layer applies weights to all nodes from the previous layer

### A simple dense layer

In [3]:
import tensorflow as tf

# Define inputs (features)
inputs = tf.constant([[1.0, 35.0]])

# Define weights 
weights = tf.Variable([[-0.05], [-0.01]])

# Define the bias 
bias = tf.Variable([0.5])

# Multiply inputs (features) by the weights
product = tf.matmul(inputs, weights)

# Define dense layer
dense = tf.keras.activations.sigmoid(product+bias)

### Defining a complete model

In [4]:
# Define input (features) layer 
inputs = tf.constant(inputs, tf.float32)

In [5]:
# Define a first dense layer
dense1 = tf.keras.layers.Dense(10, activation='sigmoid')(inputs)

In [6]:
# Define a second dense layer
dense2 = tf.keras.layers.Dense(5, activation='sigmoid')(dense1)

In [7]:
# Define output (predictions) layer
outputs = tf.keras.layers.Dense(1, activation='sigmoid')(dense2)

### High-level versus low-level approach
- High-level approach
    - High-level API operations
- Low-level approach 
    - Linear-algebraic operations

In [8]:
from tensorflow import Variable, ones, matmul, keras

In [9]:
df = pd.read_csv('data/uci_credit_card.csv')
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default.payment.next.month'],
      dtype='object')

In [10]:
borrower_features = df[['EDUCATION', 'MARRIAGE', 'AGE']].values
borrower_features = tf.convert_to_tensor(borrower_features, np.float32)
borrower_features

<tf.Tensor: id=102, shape=(30000, 3), dtype=float32, numpy=
array([[ 2.,  1., 24.],
       [ 2.,  2., 26.],
       [ 2.,  2., 34.],
       ...,
       [ 2.,  2., 37.],
       [ 3.,  1., 41.],
       [ 2.,  1., 46.]], dtype=float32)>

In [12]:
# Initialize bias1
bias1 = Variable(1.0)

# Initialize weights1 as 3x2 variable of ones
weights1 = Variable(ones((3, 2)))

# Perform matrix multiplication of borrower_features and weights1
product1 = matmul(borrower_features, weights1)

# Apply sigmoid activation function to product1 + bias1
dense1 = keras.activations.sigmoid(product1 + bias1)

# Print shape of dense1
print("\n dense1's output shape: {}".format(dense1.shape))


 dense1's output shape: (30000, 2)


In [13]:
# Initialize bias2 and weights2
bias2 = Variable(1.0)
weights2 = Variable(ones((2, 1)))

# Perform matrix multiplication of dense1 and weights2
product2 = matmul(dense1, weights2)

# Apply activation to product2 + bias2 and print the prediction
prediction = keras.activations.sigmoid(product2 + bias2)
print('\n prediction: {}'.format(prediction.numpy()[0,0]))
print('\n actual: 1')


 prediction: 0.9525741338729858

 actual: 1


In [14]:
idx = tf.constant([0,1,2,3,4])

borrower_features = tf.gather(borrower_features, idx)

borrower_features

<tf.Tensor: id=147, shape=(5, 3), dtype=float32, numpy=
array([[ 2.,  1., 24.],
       [ 2.,  2., 26.],
       [ 2.,  2., 34.],
       [ 2.,  1., 37.],
       [ 2.,  1., 57.]], dtype=float32)>

In [15]:
bias1 = Variable([0.1])
bias1

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.1], dtype=float32)>

In [16]:
weights1 = Variable([[-0.6 ,  0.6 ],
       [ 0.8 , -0.3 ],
       [-0.09, -0.08]])

weights1

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[-0.6 ,  0.6 ],
       [ 0.8 , -0.3 ],
       [-0.09, -0.08]], dtype=float32)>

In [17]:
# Compute the product of borrower_features and weights1
products1 = matmul(borrower_features, weights1)

# Apply a sigmoid activation function to products1 + bias1
dense1 = keras.activations.sigmoid(products1+bias1)

# Print the shapes of borrower_features, weights1, bias1, and dense1
print('\n shape of borrower_features: ', borrower_features.shape)
print('\n shape of weights1: ', weights1.shape)
print('\n shape of bias1: ', bias1.shape)
print('\n shape of dense1: ', dense1.shape)


 shape of borrower_features:  (5, 3)

 shape of weights1:  (3, 2)

 shape of bias1:  (1,)

 shape of dense1:  (5, 2)


In [18]:
df = pd.read_csv('data/uci_credit_card.csv')
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default.payment.next.month'],
      dtype='object')

In [19]:
features = df.columns[1:11].tolist()
features

['LIMIT_BAL',
 'SEX',
 'EDUCATION',
 'MARRIAGE',
 'AGE',
 'PAY_0',
 'PAY_2',
 'PAY_3',
 'PAY_4',
 'PAY_5']

In [20]:
borrower_features = df[features].values
borrower_features = tf.convert_to_tensor(borrower_features, np.float32)
idx = tf.constant(list(range(0,100)))

borrower_features = tf.gather(borrower_features, idx)

#borrower_features

In [21]:
from tensorflow import keras

In [22]:
# Define the first dense layer
dense1 = keras.layers.Dense(7, activation='sigmoid')(borrower_features)

# Define a dense layer with 3 output nodes
dense2 = keras.layers.Dense(3, activation='sigmoid')(dense1)

# Define a dense layer with 1 output node
predictions = keras.layers.Dense(1, activation='sigmoid')(dense2)

# Print the shapes of dense1, dense2, and predictions
print('\n shape of dense1: ', dense1.shape)
print('\n shape of dense2: ', dense2.shape)
print('\n shape of predictions: ', predictions.shape)


 shape of dense1:  (100, 7)

 shape of dense2:  (100, 3)

 shape of predictions:  (100, 1)


### What is an activation function?
- Components of a typical hidden layer
    - **Linear**: Matrix multiplication
    - **Nonlinear**: Activation function

- Why nonlinearities are important    

In [24]:
# Define example borrower features
young, old = 0.3, 0.6
low_bill, high_bill = 0.1, 0.5

# Apply matrix multiplication step for all feature combinations
young_high = 1.0*young + 2.0*high_bill
young_low = 1.0*young + 2.0*low_bill
old_high = 1.0*old + 2.0*high_bill
old_low = 1.0*old + 2.0*low_bill

In [25]:
# Difference in default predictions for young
print(young_high - young_low)

0.8


In [26]:
# Difference in default predictions for old
print(old_high - old_low)

0.8


In [27]:
# Difference in default predictions for young
print(tf.keras.activations.sigmoid(young_high).numpy() -
tf.keras.activations.sigmoid(young_low).numpy())

# Difference in default predictions for old
print(tf.keras.activations.sigmoid(old_high).numpy() -
tf.keras.activations.sigmoid(old_low).numpy())

0.16337568
0.14204389


### The sigmoid activation function 

- 

In [23]:
!../gitbsh > /dev/null 2>&1